version: '3.3'
services:
    app:
        build: .
        volumes:
            - ./src:/app/src
            - ./public:/app/public
            - ./index.ts:/app/index.ts
            - ./credentials:/app/credentials
            - ./instances:/app/instances
            - ./logs:/app/logs
            - ./maps:/app/maps
            - ./.env:/app/.env
        environment:
            - RPP_LOG_CALL_STACK=true
        container_name: rpp
        restart: always
