version: '3'
services:
  rust-plus-web:
    build: .
    container_name: rust-plus-web
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-changeme}
      - STEAM_API_KEY=${STEAM_API_KEY}
    volumes:
      - ./rust-plus.db:/app/rust-plus.db
    restart: always
